# Generated by Django 4.2.6 on 2023-11-09 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news_feed", "0002_delete_articlelastid"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Topic",
        ),
        migrations.AlterModelOptions(
            name="site",
            options={"verbose_name": "site", "verbose_name_plural": "site"},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"verbose_name": "topic", "verbose_name_plural": "topics"},
        ),
    ]
