# Generated by Django 4.2.6 on 2023-10-10 23:19

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.PositiveBigIntegerField(null=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title", unique=True
                    ),
                ),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "featured_image",
                    models.ImageField(
                        null=True, upload_to="articles/featured_images/%Y/%m/%d/"
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("modified_at", models.DateField(auto_now=True)),
                ("category_id", models.PositiveSmallIntegerField(null=True)),
                ("user_id", models.PositiveBigIntegerField(null=True)),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "Articles",
            },
        ),
    ]
