# Generated by Django 4.2.6 on 2023-10-26 23:25

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic_id", models.PositiveSmallIntegerField()),
                ("user_id", models.PositiveBigIntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title", unique=True
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("modified_at", models.DateField(auto_now=True)),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "featured_image",
                    models.ImageField(
                        null=True, upload_to="articles/featured_images/%Y/%m/%d/"
                    ),
                ),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "Articles",
            },
        ),
    ]
