# Generated by Django 4.2.6 on 2023-10-27 00:37

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="title", unique_with=("topic_id", "title")
            ),
        ),
    ]
